spring.application.name=agon
spring.thymeleaf.cache=false

# Banco de dados H2
spring.datasource.url=jdbc:h2:mem:agondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Console web do H2 (acesse em /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
